export enum UserRole {
  ADMIN = "ADMIN",
  GOVERNMENT = "GOVERNMENT",
  FARMER = "FARMER",
  COOPERATIVE = "COOPERATIVE",
  MANUFACTURER = "MANUFACTURER",
  SUPPLIER = "SUPPLIER",
  BUYER = "BUYER",
  RETAILER = "RETAILER",
  WAREHOUSE = "WAREHOUSE",
  TRANSPORT = "TRANSPORT",
  DRIVER = "DRIVER",
  BANK = "BANK",
}

export const USER_ROLES = Object.values(UserRole);
