import { PERMISSIONS, type Permission } from "@/constants/permissions";
import { UserRole } from "@/constants/roles";

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.ADMIN]: Object.values(PERMISSIONS),
  [UserRole.GOVERNMENT]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.REPORTS_READ,
  ],
  [UserRole.FARMER]: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_WRITE,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_WRITE,
  ],
  [UserRole.COOPERATIVE]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.REPORTS_READ,
  ],
  [UserRole.MANUFACTURER]: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_WRITE,
    PERMISSIONS.INVENTORY_READ,
  ],
  [UserRole.SUPPLIER]: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_WRITE,
    PERMISSIONS.ORDERS_READ,
  ],
  [UserRole.BUYER]: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_WRITE,
    PERMISSIONS.PAYMENTS_READ,
  ],
  [UserRole.RETAILER]: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.INVENTORY_READ,
  ],
  [UserRole.WAREHOUSE]: [
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_WRITE,
  ],
  [UserRole.TRANSPORT]: [PERMISSIONS.ORDERS_READ, PERMISSIONS.REPORTS_READ],
  [UserRole.DRIVER]: [PERMISSIONS.ORDERS_READ],
  [UserRole.BANK]: [PERMISSIONS.PAYMENTS_READ, PERMISSIONS.REPORTS_READ],
};
